name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  uuid: ^4.0.0
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.6
  cupertino_icons: ^1.0.2
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
